### ISSUE TITLE
Pagination on post list

### ISSUE THREAD

**Issue by angezanetti** [zerostaticthemes/hugo-winston-theme#10]
The pagination seems to be only active on the homepage. It's hard to understand why, even more with the big titles in the list page. 
I can't imagine how long I should scroll for a blog with 50 posts :)

The fix is pretty easy to do tho, should I create a PR?

**Comment by JugglerX** [comment]
@angezanetti yeah we definitely need pagination on the blog. A PR would be amazing.

**Comment by JugglerX** [comment]
Fixed in 83eb066c546f4edbaee35babad6fa542aa894103
