### ISSUE TITLE
Blog navbar does not remain active on post

### ISSUE THREAD

**Issue by gwo0d** [zerostaticthemes/hugo-winston-theme#18]
When on individual posts, the parent link in the navbar does not remain active, only doing so on the index page. See images for example.

[Index Page](https://gwood.dev/blog/)
[Post Page](https://gwood.dev/blog/2021/10/gpg-tutorial-command-line/)

**Comment by JugglerX** [comment]
Fixed in 9edacfbc30f318fa8fc6e2a347fc9955bd0eb9be
