### ISSUE TITLE
Posts not scaling in mobile

### ISSUE THREAD

**Issue by ghost** [zerostaticthemes/hugo-winston-theme#21]
The Post title and body are out of frame. I have to zoom out to see the full post, which seems to glitch and doesn't fit in the frame while the screen is in portrait mode. Landscape mode works fine. Any lead on how to fix it?
- [Portrait_mode.pdf](https://github.com/zerostaticthemes/hugo-winston-theme/files/9427601/Portrait_mode.pdf)
- [Landscape_mode.pdf](https://github.com/zerostaticthemes/hugo-winston-theme/files/9427603/Landscape_mode.pdf)

**Comment by JugglerX** [comment]
I'm unable to reproduce. can you provide a working URL with the problem or more information on the browser/device
