### ISSUE TITLE
Failed during stage 'preparing repo': Error checking out submodules: fatal: No url found for submodule path 'themes/hugo-winston-theme' in .gitmodules

### ISSUE THREAD

**Issue by enochterrymize** [zerostaticthemes/hugo-winston-theme#26]

**Comment by JugglerX** [comment]
maybe a git submodule issue?

**Comment by sedbytes** [comment]
I fixed it by running `git submodule add https://github.com/zerostaticthemes/hugo-winston-theme themes/hugo-winston-theme` instead of the `git clone` mentioned in the README.
