### ISSUE TITLE
Copy statement points to wrong path on Hugo Themes page

### ISSUE THREAD

**Issue by annagodwin** [zerostaticthemes/hugo-winston-theme#29]
Hello! 

Wasn't sure where to leave this since this is occurring on the Hugo Themes page for Hugo Winston Theme 
https://themes.gohugo.io/themes/hugo-winston-theme/

When you get the copy statement in the Installation guide it calls `hugo-serif-theme` instead of `hugo-winston-theme`

Current: `cp -a themes/hugo-serif-theme/exampleSite/. .`
Change to:  `cp -a themes/hugo-winston-theme/exampleSite/. .`

I checked the `README.md` here on the Github repo, and the Installation guide's copy statement is correct.

Thanks for the theme!

**Comment by JugglerX** [comment]
This was recently updated on this repo, looks like the hugo themes site needs a rebuild before it updates.
