### ISSUE TITLE
Changing the color border

### ISSUE THREAD

**Issue by hathawayj** [zerostaticthemes/hugo-winston-theme#3]
Is there a parameter to change the color of the border and dot?

**Comment by hathawayj** [comment]
@JugglerX ?

**Comment by toringe** [comment]
@hathawayj look for the `--highlight-color` parameter.

**Comment by JugglerX** [comment]
I've made the highlight color configurable in the `config.toml` c2d76d94697660a4e40a1c2ef740a6c3267aaacc
