### ISSUE TITLE
How to add tags to posts

### ISSUE THREAD

**Issue by DamBasement** [zerostaticthemes/hugo-winston-theme#32]
Hi, 
I was trying to add tags on posts. I can see the pages tags and categories successfully created after adding these lines in the config.toml
```
[taxonomies]
  tag = "tags"
  category = "categories"
```
Anyway, I can't render the tags in the post itself. Do you know how to achieve it? 

Thanks a lot!

**Comment by DamBasement** [comment]
@JugglerX I am trying to work on it. So far no luck but I am following HUGO documentation in order to implement it with _/layouts_. Let me know if there is something specific about your template (which is great BTW) to know that can help. I saw that many templates should render this automatically. Cheers!

**Comment by JugglerX** [comment]
@barry-hennessy added this feature in #25
