### ISSUE TITLE
Support extending the <head> section with custom links

### ISSUE THREAD

**Issue by ITAYC0HEN** [zerostaticthemes/hugo-winston-theme#34]
Using a partial, you can help users (like myself) extending some parts of the header. In your <head> section, you can include an optional partial by the user, called header.extended.html or something like this.
This way, we can add more things like custom scripts, fonts, etc

**Comment by JugglerX** [comment]
@ITAYC0HEN I added the ability to extend the head and footer. You can place you own `layouts/partials/extended-footer.html` and `layouts/partials/extended-head.html`

**Comment by ITAYC0HEN** [comment]
Thank you!
Correcting for future visitors: it's layouts/partials/**extend**-footer.html and layouts/partials/**extend**-head.html
